Not Found: /shop/custom_products/
Not Found: /shop/custom_products/
Not Found: /shop/custom_products/
Not Found: /shop/custom_products/
Internal Server Error: /custom_products/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 32, in custom_products
    t = loader.get_template('custom_products.html')
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 282, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 60, in extend_nodelist
    super(DebugParser, self).extend_nodelist(nodelist, node, token)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 308, in extend_nodelist
    "in the template." % node)
TemplateSyntaxError: <ExtendsNode: extends "base.html"> must be the first tag in the template.
Not Found: /favicon.ico
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/views.py", line 16, in index
    return HttpResponse(t.render(c))
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/classytags/helpers.py", line 78, in render_tag
    data = self.get_context(context, **kwargs)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/shop/templatetags/shop_tags.py", line 24, in get_context
    request = context['request']
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: 'request'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 5, in <module>
    admin.site.register(Book, Pencil)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/polymorphic/base.py", line 246, in __getattribute__
    return super(PolymorphicModelBase, self).__getattribute__(name)
AttributeError: type object 'Pencil' has no attribute 'validate'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 5, in <module>
    admin.site.register(Book, Pencil)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/polymorphic/base.py", line 246, in __getattribute__
    return super(PolymorphicModelBase, self).__getattribute__(name)
AttributeError: type object 'Pencil' has no attribute 'validate'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 5, in <module>
    admin.site.register(Book, Pencil)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/polymorphic/base.py", line 246, in __getattribute__
    return super(PolymorphicModelBase, self).__getattribute__(name)
AttributeError: type object 'Pencil' has no attribute 'validate'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 5, in <module>
    admin.site.register(Book, Pencil)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/polymorphic/base.py", line 246, in __getattribute__
    return super(PolymorphicModelBase, self).__getattribute__(name)
AttributeError: type object 'Pencil' has no attribute 'validate'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 5, in <module>
    admin.site.register(Book, Pencil)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/polymorphic/base.py", line 246, in __getattribute__
    return super(PolymorphicModelBase, self).__getattribute__(name)
AttributeError: type object 'Pencil' has no attribute 'validate'
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 5, in <module>
    admin.site.register(Book, Pencil)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 92, in register
    admin_class.validate(model)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/polymorphic/base.py", line 246, in __getattribute__
    return super(PolymorphicModelBase, self).__getattribute__(name)
AttributeError: type object 'Pencil' has no attribute 'validate'
Internal Server Error: /shop/products/qwewqeqwe/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 7
SyntaxError: Non-ASCII character '\xd0' in file /home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 7
SyntaxError: Non-ASCII character '\xd0' in file /home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 7
SyntaxError: Non-ASCII character '\xd0' in file /home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 7
SyntaxError: Non-ASCII character '\xd0' in file /home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 3, in <module>
    from models import Book, Pencil
ImportError: cannot import name Pencil
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 10, in <module>
    admin.site.register(BookAdmin,)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 71, in register
    for model in model_or_iterable:
TypeError: 'RenameBaseModelAdminMethods' object is not iterable
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 10, in <module>
    admin.site.register(BookAdmin)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 71, in register
    for model in model_or_iterable:
TypeError: 'RenameBaseModelAdminMethods' object is not iterable
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 10, in <module>
    admin.site.register(BookAdmin)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 71, in register
    for model in model_or_iterable:
TypeError: 'RenameBaseModelAdminMethods' object is not iterable
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 10, in <module>
    admin.site.register(BookAdmin)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 71, in register
    for model in model_or_iterable:
TypeError: 'RenameBaseModelAdminMethods' object is not iterable
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 10, in <module>
    admin.site.register(BookAdmin)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 71, in register
    for model in model_or_iterable:
TypeError: 'RenameBaseModelAdminMethods' object is not iterable
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 10, in <module>
    admin.site.register(BookAdmin)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 71, in register
    for model in model_or_iterable:
TypeError: 'RenameBaseModelAdminMethods' object is not iterable
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 10, in <module>
    admin.site.register(BookAdmin)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 71, in register
    for model in model_or_iterable:
TypeError: 'RenameBaseModelAdminMethods' object is not iterable
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/urls.py", line 4, in <module>
    admin.autodiscover()
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 29, in autodiscover
    import_module('%s.admin' % app)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest/shoptest/admin.py", line 10, in <module>
    admin.site.register(BookAdmin)
  File "/home/kalinin/.virtualenvs/shoptest_project/shoptest_env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 71, in register
    for model in model_or_iterable:
TypeError: 'RenameBaseModelAdminMethods' object is not iterable
